ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  server-name:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Role: 'acs:ram::1911607420711126:role/new-service1606871905191-role'
      VpcConfig:
        VpcId: vpc-uf6d791e7ysear9mwu6ac
        VSwitchIds:
          - vsw-uf6cc40fjn4ljk3whlzdo
        SecurityGroupId: sg-uf6i1r3ycwoin71f7dr7
      InternetAccess: true
    function-name:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: server.handler
        Runtime: custom
        Timeout: 30
        MemorySize: 1024
        InstanceConcurrency: 10
        EnvironmentVariables:
          LD_LIBRARY_PATH: >-
            /code/.fun/root/usr/local/lib:/code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code/.fun/root/lib:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/python/lib/python2.7/site-packages:/code/.fun/root/python/lib/python3.6/site-packages:/code:/code/lib:/usr/local/lib
          NODE_PATH: '/code/node_modules:/usr/local/lib/node_modules'
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code:/code/node_modules/.bin:/code/.fun/python/bin:/code/.fun/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin
          PYTHONUSERBASE: /code/.fun/python
      Events:
        http-function-name:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
